apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: j3y9crx9c-dotnet-basic
  janus-idp.io/tekton: j3y9crx9c-dotnet-basic
  backstage.io/kubernetes-id: j3y9crx9c-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: j3y9crx9c-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
